name: "Install dependencies"
description: "Prepare repository and all dependencies"

runs:
  using: "composite"
  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@v3

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        cache: pnpm
        node-version: 20

    - name: Set up Bun
      uses: oven-sh/setup-bun@v1

    - name: Install dependencies
      shell: bash
      run: pnpm install